[build-system]
requires = ["setuptools>=64.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "baseballcomparator"
version = "1.0.0"
dependencies = [
    "Flask",
    "requests",
]
requires-python = ">=3.8"

[tool.setuptools]
packages = ["baseballcomparator"]